replicaCount: 1
image:
  repository: Jenkins_devops_exams/movie-service
  tag: latest
service:
  type: ClusterIP
  port: 8000
env:
  DATABASE_URI: postgresql://movie_db:password@movie_db/movie_db_dev
  CAST_SERVICE_HOST_URL: http://cast_service:8000/api/v1/casts/
